export const projects = [
  {
    id: 1,
    images: [
      require("./media/images/beach_house/backyard.jpg"),
      require("./media/images/beach_house/backyard2.jpg"),
      require("./media/images/beach_house/backyardbar.jpg"),
      require("./media/images/beach_house/backyardbar1.jpg"),
      require("./media/images/beach_house/backyardbar2.jpg"),
      require("./media/images/beach_house/outdoorbar1.jpg"),
      require("./media/images/beach_house/cabana.jpg"),
      require("./media/images/beach_house/sauna.jpg"),
      require("./media/images/beach_house/dock.jpg"),
      require("./media/images/beach_house/dock2.jpg"),
      require("./media/images/beach_house/exterior.jpg"),
      require("./media/images/beach_house/exterior2.jpg"),
      require("./media/images/beach_house/fountains.jpg"),
      require("./media/images/beach_house/pavingstones.jpg"),
      require("./media/images/beach_house/fencing.jpg"),
      require("./media/images/beach_house/frontentrancebefore.jpg"),
      require("./media/images/beach_house/mainentrance.jpg"),
      require("./media/images/beach_house/mainhall.jpg"),
      require("./media/images/beach_house/stairs.jpg"),
      require("./media/images/beach_house/glassfloor1.jpg"),
      require("./media/images/beach_house/glassfloor2.jpg"),
      require("./media/images/beach_house/glassfloor3.jpg"),
      require("./media/images/beach_house/glassfloor4.jpg"),
      require("./media/images/beach_house/kitchen.jpg"),
      require("./media/images/beach_house/kitchen2.jpg"),
      require("./media/images/beach_house/livingroom.jpg"),
      require("./media/images/beach_house/livingroom1.jpg"),
      require("./media/images/beach_house/before_after.jpg"),
    ],
    projectBody:
      "This project involved transforming an old beachfront home into a space suitable for both business events and family gatherings. Being so close to the water presented several unique challenges, but the results were well worth it. The entire interior layout was redesigned, with additions made to the sides, front deck, and garage. A new roof was installed, the driveway was replaced with beautiful paving stones, and new structures and outdoor spaces were created in the backyard.",
    type: "Full Home Renovation",
    title: "(Beach House)",
    stars: "",
  },
  {
    id: 2,
    images: [
      require("./media/images/residential_house/backdeck.jpg"),
      require("./media/images/residential_house/backdeck2.jpg"),
      require("./media/images/residential_house/backdeck3.jpg"),
      require("./media/images/residential_house/cedar_soffit.jpg"),
      require("./media/images/residential_house/lounging.jpg"),
      require("./media/images/residential_house/pergula.jpg"),
      require("./media/images/residential_house/pargula.jpg"),
      require("./media/images/residential_house/pergula2.jpg"),
      require("./media/images/residential_house/garden_bed1.jpg"),
      require("./media/images/residential_house/garden_bed2.jpg"),
      require("./media/images/residential_house/newdoor.jpg"),
      require("./media/images/residential_house/hallway.jpg"),
      require("./media/images/residential_house/livingroom.jpg"),
      require("./media/images/residential_house/bathroom.jpg")
    ],
    projectBody:
      "This was a fun project focused on refreshing an outdated family home and bringing back a sense of life and luxury. The renovation included two fully refurbished bedrooms, a home theater, a sauna, a remodeled bathroom, and a new crafting space in the basement. Upstairs, we added a brand new living area, an open-concept kitchen, a modern office, and a sleek bathroom complete with a stackable washer and dryer. New doors, new flooring, and a full interior repaint tied everything together—capped off with a beautiful outdoor space, perfect for enjoying the Okanagan summer!",
    type: "Full Home Renovation",
    title: "(Residential Home)",
    stars: "",
  },
  {
    id: 3,
    images: [
      require("./media/images/exteriors/exterior.jpg"),
      require("./media/images/exteriors/exterior_before.jpg"),
      require("./media/images/exteriors/exterior_before1.jpg"),
      require("./media/images/exteriors/exterior_before2.jpg"),
      require("./media/images/exteriors/exterior3.jpg"),
      require("./media/images/exteriors/exterior4.jpg"),
      require("./media/images/exteriors/exterior6.jpg"),
      require("./media/images/exteriors/exterior1.jpg"),
      require("./media/images/exteriors/exterior7.jpg"),
      require("./media/images/exteriors/exterior5.jpg"),
      require("./media/images/exteriors/exterior8.jpg"),
      require("./media/images/exteriors/exterior2.jpg"),
      require("./media/images/exteriors/exterior9.jpg"),
      require("./media/images/exteriors/garage.jpg"),
      require("./media/images/exteriors/exterior10.jpg"),
      require("./media/images/exteriors/cedarsoffit.jpg")
    ],
    projectBody:
      "RTS Solutions began with a focus on exteriors. If you have a bold vision for your home’s exterior and others say it can’t be done—we’ll prove them wrong. With hundreds of successful projects and a lifetime of experience, we make the impossible possible.",
    type: "Exteriors",
    stars: "",
  },
  {
    id: 4,
    images: [
      require("./media/images/kitchens/kitchen11.jpg"),
      require("./media/images/kitchens/kitchen4.jpg"),
      require("./media/images/kitchens/kitchen8.jpg"),
      require("./media/images/kitchens/kitchen2.jpg"),
      require("./media/images/kitchens/kitchen6.jpg"),
      require("./media/images/kitchens/kitchen.jpg"),
      require("./media/images/kitchens/kitchen3.jpg"),
      require("./media/images/kitchens/kitchen5.jpg"),
      require("./media/images/kitchens/kitchen7.jpg")
    ],
    projectBody:
      "Is your outdated kitchen draining the fun from cooking and entertaining? We’ll design a functional, modern space that brings the joy back. Whether you’re dreaming of an outdoor kitchen, a compact layout, or a butler pantry, we’ve done it all. Let’s find what works best for your space—get in touch today!",
    type: "Kitchens",
    stars: "",
  },
  {
    id: 5,
    images: [
      require("./media/images/fencing/fencing.jpg"),
      require("./media/images/fencing/fencing4.jpg"),
      require("./media/images/fencing/fencing7.jpg"),
      require("./media/images/fencing/fencing6.jpg"),
      require("./media/images/fencing/fencing5_n.jpg"),
      require("./media/images/fencing/fencing9.jpg"),
      require("./media/images/fencing/fencing8.jpg"),
      require("./media/images/fencing/fencing2.jpg"),
      require("./media/images/fencing/fencing3.jpg"),
    ],
    projectBody:
      "Dealing with nosey neighbors? Tired of dogs leaving surprises on your lawn? Or maybe the neighbor’s sprinklers are ruining your garden party? We’ve seen it all—and we’ve got the fence solutions to match. Whether you're upgrading an existing fence or installing a brand new one, we've got you covered.",
    type: "Fencing",
    stars: "",
  },
  {
    id: 6,
    images: [
      require("./media/images/other_spaces/bathroom.jpg"),
      require("./media/images/other_spaces/bathroom2.jpg"),
      require("./media/images/other_spaces/bathroom5.jpg"),
      require("./media/images/other_spaces/bathroom6.jpg"),
      require("./media/images/other_spaces/livingspace3.jpg"),
      require("./media/images/other_spaces/livingspace4.jpg"),
      require("./media/images/other_spaces/livingspace7.jpg"),
      require("./media/images/other_spaces/livingspace8.jpg"),
      require("./media/images/other_spaces/lvingspace5.jpg"),
      require("./media/images/other_spaces/newstairs.jpg"),
      require("./media/images/other_spaces/window.jpg"),
      require("./media/images/other_spaces/kitchenbefore_after.jpg")
    ],
    projectBody: "No job is too big or too small. Need a new closet? New stairs? A fresh shower install? No problem. With over 30 years of experience working on both new and older homes, we can make any space work for you. Not sure what your home needs? Reach out—we’ll help you find the perfect fit.",
    type: "Other Spaces"
  }
];
